### ISSUE TITLE
Windows and Linux issues collection

### ISSUE THREAD

**Issue by silvanocerza** [arduino/arduino-language-server#46] opened 2021-01-07 17:07 UTC
Windows specific issues:

* ~~Problems window shows outdated errors even after they have been solved~~
* ~~Autoformat doesn't work~~
* ~~Problems windows shows error in `not-ino` file:~~
```
In included file: 'vcruntime.h' file not found

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\corecrt.h:10:10:
note: error occurred here
```

* Including a new library doesn't restart the LS so definition in that header are not shown on autocomplete, selecting another board solves that since it forces a restart of the LS

* ~~The LS crashes often even with minimal output, this is probably caused by the fact that paths are escaped multiple times, see last lines of following log: [inols-err.log](https://github.com/bcmi-labs/arduino-language-server/files/5782940/inols-err.log)~~

* ~~Symbols like `pinMode`, `digitalWrite` and `delay` are not recognized by the LS, probably caused by escaping paths multiple times.~~
![image](https://user-images.githubusercontent.com/3314350/103921539-ec42e400-5112-11eb-8df0-b3f35d1d3b99.png)

* ~~Often errors are highlighted in the text editor but are shown in the Problems window, this might be caused by the escaping paths multiple times too.~~

Both in Linux and Windows:

* No output from the Arduino Language Server is shown but logs are still written to file in the sketch folder. After triggering output for some other reason, like installing a core, the LS output is shown.

* ~~`Serial` is never autocompleted and not recognized as a known symbol.~~

**Comment by per1234** [comment] 2022-02-13 19:23
I'm closing this in favor of dedicated issues in order to facilitate the maintenance, tracking, and support for these issues.

> Including a new library doesn't restart the LS so definition in that header are not shown on autocomplete, selecting another board solves that since it forces a restart of the LS

Now tracked in the dedicated issue: https://github.com/arduino/arduino-ide/issues/670

> No output from the Arduino Language Server is shown but logs are still written to file in the sketch folder. After triggering output for some other reason, like installing a core, the LS output is shown.

The significant work done on the Arduino Language Server since the time this issue was created have fixed issues that caused these symptoms. It is possible there are still some that remain. If anyone is able to still reproduce the problem, please open an issue with instructions we can follow to reproduce it.

> LS is often slow, declaring a function and writing an invocation fast enough doesn't show that function in the autocomplete window right away

Now tracked in the dedicated issue: https://github.com/arduino/arduino-language-server/issues/98

> "Verify WiFi101.h is shown in autocomplete window" step fails. I never get any autocomplete for header files in `#include` directives.

I do get them now for files in the include search paths. The old manual testing test case still fails because the file is not in the include path due to requiring [library discovery](https://arduino.github.io/arduino-cli/dev/sketch-build-process/#dependency-resolution).

For example, you won't get a suggestion for `Ethernet.h` with this code:

```cpp
#include <Ethern
void setup() {}
void loop() {}
```
Because the source folder of the Ethernet library is not in the default include search paths.

However, you will get it for `EthernetClient.h` here:

```cpp
#include <Ethernet.h>
#include <EthernetCli
void setup() {}
void loop() {}
```

The reason is that the `#include` directive for `Ethernet.h` caused the "Ethernet" library source folder to be added to the include search paths by library discovery.

I think the current capabilities for `#include` directives are sufficient, so will consider this one resolved.

> inside an `.ino` fail that is not the main it gets formatted to

I suspect it is the same issue that causes the symptom described here: https://github.com/arduino/arduino-ide/issues/543

**Closed by per1234** 2022-02-13 19:23 UTC
